language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - python3 -m pip install -r requirements.txt
  - git clone https://github.com/SCOTT-HAMILTON/merge-keepass
  - cd merge-keepass
  - python3 setup.py install

# command to run tests
script:
  - python3 setup.py install
